DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - REPOSITORY_TRIVY # Terraform linter
  - YAML_YAMLLINT
  - CSHARP_DOTNET_FORMAT
  - CSHARP_ROSLYNATOR
  - JAVASCRIPT_STANDARD

